name: Generate publiccode.yaml and .env files

# Controls when the workflow will run
on:
  # Allows this workflow to be used in other repositories
  workflow_call:

# Uses the default testing workflow from https://github.com/CommonGateway/workflows 
jobs:

  create-publiccode-and-env:
    name: Create publiccode.yaml and .env
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - name: Create publiccode.yaml
        uses: 1arp/create-a-file-action@0.2
        with:
          path: ''
          file: 'publiccode.yaml'
          content: |
            publiccodeYmlVersion: "0.1"

            name: "${{ github.event.repository.name }}"
            url: "https://github.com/${{ github.repository }}"
            releaseDate: "2022-06-04"

            softwareType: configurationFiles

            inputTypes:
              - application/json
              - application/xml

            outputTypes:
              - application/json

            platforms:
              - web
              
            categories:
              - collaboration
              - it-development
              
            developmentStatus: beta

            description:
              nl:
                shortDescription: "${{ github.event.repository.name }}"
                documentation: 'https://redocly.github.io/redoc/?url=https://raw.githubusercontent.com/${{ github.repository }}/main/OAS.yaml&nocors'
                apiDocumentation: 'https://raw.githubusercontent.com/${{ github.repository }}/main/OAS.yaml'
                # testDataLocation: 'https://raw.githubusercontent.com/${{ github.repository }}/main/data/data.json'
              en:
                shortDescription: "${{ github.event.repository.name }}"
                documentation: 'https://redocly.github.io/redoc/?url=https://raw.githubusercontent.com/${{ github.repository }}/main/OAS.yaml&nocors'
                apiDocumentation: 'https://raw.githubusercontent.com/${{ github.repository }}/main/OAS.yaml'
                # testDataLocation: 'https://raw.githubusercontent.com/${{ github.repository }}/main/data/data.json'

            dependsOn:
              open:
                - name: common-gateway
                  versionMin: 1.0.0

      - name: Create .env
        uses: 1arp/create-a-file-action@0.2
        with:
          path: ''
          file: '.env'
          content: |
            ##################################################
            # Application settings
            ##################################################
            # This section contains generic settings for your application

            # The shortcode for this component, should be a small set of letters reprecentint the application (use only letters, capitals and spaces)
            APP_NAME=${{ github.event.repository.name }}

            APP_NAME_TECHNCICAL=${{ github.event.repository.name }}


            # The description for this api
            APP_DESCRIPTION=${{ github.event.repository.name }}
            # The current version of the application
            APP_VERSION=V1.0
            APP_MAJOR_VERSION=v1

            # The type either application or component
            APP_TYPE=component

            ##################################################
            # Security
            ##################################################
            # The urls/ip's and hosts on wich this api is available
            TRUSTED_PROXIES=10.0.0.0/8,172.16.0.0/12,192.168.0.0/16
            TRUSTED_HOSTS=^.+$
            # Key that other applications can use to connect to this application (hier mag wel iets meer toelichtende tekst bij)
            APP_APPLICATION_KEY=45c1a4b6-59d3-4a6e-86bf-88a872f35845

            ##################################################
            # Licensing / Copyright
            ##################################################
            # The owner (copyright holder) of the code base
            OWNER_NAME=Conduction
            OWNER_URL=https://www.conduction.nl

            # The licence type (the licence file should always be located in the root of the code base as LICENCE.md)
            LICENCE_NAME=EUPL

            ##################################################
            # Helm / Artifacthub settings
            ##################################################

            # The logo for this application (used on the api doc page, in helm files and on Artifacthub)
            APP_LOGO=https://conductionnl.github.io/images/conduction_avatar_blue_on_transparant.svg
            # The addres where more information about this application can be found (used on the api doc page, in helm files and on Artifacthub)
            APP_HOME=https://www.conduction.nl
            # The id of this application on https://artifacthub.io/ (use false if you do not want to  use artifacthub)
            ARTIFACTHUB_ID=
            # name of the organization leave blank to not sure organization
            ARTIFACTHUB_USER=
            ##################################################
            # Routing and domain settings
            ##################################################

            # The domain for this component (do not include a subdomain, this will hamper certification generation)
            APP_DOMAIN=conduction.nl

            # The subdomain for this component (should be false if you want to use www)
            APP_URL=http://localhost
            APP_SUBDOMAIN=${{ github.event.repository.name }}
            APP_SUBPATH=${{ github.event.repository.name }}
            APP_SUBPATH_ROUTING=true

            APP_DEMO=${{ github.event.repository.name }}.commonground.nu

            # Whether or not the component is to be exposed publicly
            APP_WEB=false
            # Whether or not to default cluster internal calls on kubernetes
            APP_INTERNAL=false

            ##################################################
            # Github settings
            ##################################################
            # organization/repo-name
            APP_CHART=${{ github.repository }}
            # The GIT Repository for this component (The place where the sourcecode is stored)
            APP_REPRO=https://github.com/${{ github.repository }}

            ##################################################
            # Docker settings
            ##################################################

            CONTAINER_REGISTRY_BASE=ghcr.io/conductionnl
            HELM_REPOSITORY=https://raw.githubusercontent.com/${{ github.repository }}/master/api/helm/
            CONTAINER_PROJECT_NAME=${{ github.event.repository.name }}
            ##################################################
            # Notifcation settings
            ##################################################

            NOTIFICATION_ENABLED=false

            ##################################################
            # Authorization settings
            ##################################################

            AUTH_ENABLED=false

            ##################################################
            # Development Settings
            ##################################################
            # This sections contains options for configuring your local development environment

            APP_ID=
            # Do you want to display the symfony debug toolbar?
            APP_DEBUG=1
            # What is the enviroment type you want to use for local production? (choose between dev, stag, prod, acce or test)
            APP_ENV=dev
            # We use a build to tag images, this is swithced to the version on master and to env on other branches
            APP_BUILD=dev
            # Do you want to use caching? true/false
            APP_CACHE=false
            # Whether or not to include ALL datafixtures in a build (used for testing purposes in ci/cd)
            APP_BUILD_ALL_FIXTURES=true
            # Whether to enable or disable audit trials
            AUDITTRAIL_ENABLED=false
            # the duration of the session in seconds
            APP_SESSION_DURATION=900


            ##################################################
            # RabbitMQ
            ##################################################
            RABBITMQ_USERNAME=common-gateway
            RABBITMQ_PASSWORD=changeme!

            ##################################################
            # Publiccode
            ##################################################
            PUBLICCODE="https://raw.githubusercontent.com/${{ github.repository }}/main/publiccode.yaml"


      - name: Commit and push changes
        run: |
          git config --global user.name "${{ github.actor }}"
          git config --global user.email "${{ github.event.pusher.email }}"

          git add publiccode.yaml
          git commit -m "Auto updated publiccode.yaml"
          git add .env
          git commit -m "Auto updated .env"
          git push
